version: '1.0.0'

services:
    database:
      image: postgres:16
      environment: 
        TZ: America/Salvador
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
      ports:
        - '5432:5432'
      expose:
        - '5432'
    web:
      build: .
      stdin_open: true
      tty: true
      entrypoint: config/setup_app.sh
      command: bash -c "rails s -p 3000 -b '0.0.0.0'"
      environment: 
        TZ: America/Salvador
      env_file:
        - ./.env.development
      volumes:
        - .:/home/app/web
      ports:
        - '3000:3000'